# Experiment 4: Assessing Classifier Overfitting Tendency

In [1]:
# Importing necessary libraries and packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from custom_functions.RepetitiveTasks import imputation, remove_class, encoding, separating, classification_evaluation, kfold_cross_validation, oversampling

# 1. Mushroom Dataset

In [2]:
# Loading the dataset
df = pd.read_csv("datasets/mushrooms.csv")

In [3]:
# Displaying the first five records of the dataset
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(8124, 23)

In [5]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [6]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [7]:
# Encoding the attributes of the dataset
df = encoding(df)

In [8]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [9]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [10]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.89461538 0.90230769 0.90307692 0.89846154 0.8960739 ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.8989070882927697                    |
|                         |                                                          |
|     Precision Score     | [0.89461538 0.90230769 0.90307692 0.89846154 0.8960739 ] |
|                         |                                                          |
| Average Precision Score |                    0.8989070882927697                    |
|                         |                                                          |
|       Recall Score      | [0.89461538 0.90230769 0.90307692 0.89846154 0.8960739 ] |
|                         |                                                          |
|   Average Recall Score  |                    0.8989070882927697                    |
|                         |                                                          |
|         F1 Score        | [0.89461538 0.90230769 0.90307692 0.89846154 0.8960739 ] |
|                         |                                                          |
|     Average F1 Score    |                    0.8989070882927697                    |
+-------------------------+----------------------------------------------------------+

In [12]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [13]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.011905
1,K-Nearest Neighbours,0.995077,0.995077,0.995077,0.995077,0.995255,0.990192,0.094743
2,Support Vector Machine,0.993231,0.993231,0.993231,0.993231,0.993106,0.986458,0.998292
3,Naive Bayes Classifier,0.966769,0.966769,0.966769,0.966769,0.965658,0.934813,0.011431
4,Logistic Regression,0.947692,0.947692,0.947692,0.947692,0.947734,0.895278,1.089830
5,Multi Layer Perceptron,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,14.966902
6,AdaBoost Classifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.254933
7,Random Forest,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.226301
8,Gradient Boosting,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.426352
9,Extra Trees,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.198434
10,XGBoost,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.138781
11,Custom Naive Bayes Classifier,0.966769,0.966769,0.966769,0.966769,0.965658,0.934813,1.248072
12,Count-Based Classifier,0.894769,0.894769,0.894769,0.894769,0.890757,0.805112,0.681799

# 2. Car Evaluation Dataset

In [14]:
# Loading the dataset
df = pd.read_csv("datasets/car.csv")

In [15]:
# Displaying the first five records of the dataset
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [16]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(1728, 7)

In [17]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [18]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [19]:
# Encoding the attributes of the dataset
df = encoding(df)

In [20]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [21]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [22]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [23]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.64903226 0.64129032 0.63565891 0.63436693 0.61886305] |
|                         |                                                          |
|  Average Accuracy Score |                     0.63584229390681                     |
|                         |                                                          |
|     Precision Score     | [0.64903226 0.64129032 0.63565891 0.63436693 0.61886305] |
|                         |                                                          |
| Average Precision Score |                     0.63584229390681                     |
|                         |                                                          |
|       Recall Score      | [0.64903226 0.64129032 0.63565891 0.63436693 0.61886305] |
|                         |                                                          |
|   Average Recall Score  |                     0.63584229390681                     |
|                         |                                                          |
|         F1 Score        | [0.64903226 0.64129032 0.63565891 0.63436693 0.61886305] |
|                         |                                                          |
|     Average F1 Score    |                     0.63584229390681                     |
+-------------------------+----------------------------------------------------------+

In [25]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [26]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.997934,0.997934,0.997934,0.997934,0.998640,0.997246,0.009753
1,K-Nearest Neighbours,0.920455,0.920455,0.920455,0.920455,0.978496,0.897232,0.036125
2,Support Vector Machine,0.988636,0.988636,0.988636,0.988636,0.999768,0.984882,0.523046
3,Naive Bayes Classifier,0.878099,0.878099,0.878099,0.878099,0.973252,0.839413,0.007754
4,Logistic Regression,0.553719,0.553719,0.553719,0.553719,0.772546,0.408401,0.032180
5,Multi Layer Perceptron,0.992769,0.992769,0.992769,0.992769,0.999929,0.990363,2.566466
6,AdaBoost Classifier,0.731405,0.731405,0.731405,0.731405,0.869081,0.658581,0.137436
7,Random Forest,0.994835,0.994835,0.994835,0.994835,0.999885,0.993115,0.196053
8,Gradient Boosting,0.986570,0.986570,0.986570,0.986570,0.999646,0.982158,0.640781
9,Extra Trees,0.991736,0.991736,0.991736,0.991736,0.999851,0.988972,0.160415
10,XGBoost,0.998967,0.998967,0.998967,0.998967,1.000000,0.998622,0.511687
11,Custom Naive Bayes Classifier,0.878099,0.878099,0.878099,0.878099,0.973234,0.839413,0.374979
12,Count-Based Classifier,0.625000,0.625000,0.625000,0.625000,0.922065,0.536744,0.197724

# 3. Breast Cancer Dataset

In [27]:
# Loading the dataset
df = pd.read_csv("datasets/breast-cancer.csv")

In [28]:
# Displaying the first five records of the dataset
df.head()

,class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no

In [29]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(286, 10)

In [30]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [31]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

no-recurrence-events    201
recurrence-events        85
Name: class, dtype: int64

In [32]:
# Encoding the attributes of the dataset
df = encoding(df)

In [33]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [34]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [35]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [36]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.63076923 0.59375    0.71875    0.640625   0.6875    ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.6542788461538461                    |
|                         |                                                          |
|     Precision Score     | [0.63076923 0.59375    0.71875    0.640625   0.6875    ] |
|                         |                                                          |
| Average Precision Score |                    0.6542788461538461                    |
|                         |                                                          |
|       Recall Score      | [0.63076923 0.59375    0.71875    0.640625   0.6875    ] |
|                         |                                                          |
|   Average Recall Score  |                    0.6542788461538461                    |
|                         |                                                          |
|         F1 Score        | [0.63076923 0.59375    0.71875    0.640625   0.6875    ] |
|                         |                                                          |
|     Average F1 Score    |                    0.6542788461538461                    |
+-------------------------+----------------------------------------------------------+

In [38]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [39]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.641975,0.641975,0.641975,0.641975,0.650000,0.300000,0.005640
1,K-Nearest Neighbours,0.777778,0.777778,0.777778,0.777778,0.786111,0.570815,0.006565
2,Support Vector Machine,0.641975,0.641975,0.641975,0.641975,0.647222,0.293180,0.014601
3,Naive Bayes Classifier,0.716049,0.716049,0.716049,0.716049,0.713889,0.426725,0.005269
4,Logistic Regression,0.679012,0.679012,0.679012,0.679012,0.675000,0.350000,0.006001
5,Multi Layer Perceptron,0.753086,0.753086,0.753086,0.753086,0.761111,0.520938,10.947710
6,AdaBoost Classifier,0.679012,0.679012,0.679012,0.679012,0.680556,0.358902,0.057235
7,Random Forest,0.740741,0.740741,0.740741,0.740741,0.738889,0.476602,0.126741
8,Gradient Boosting,0.703704,0.703704,0.703704,0.703704,0.702778,0.403814,0.063922
9,Extra Trees,0.765432,0.765432,0.765432,0.765432,0.763889,0.526479,0.065966
10,Custom Naive Bayes Classifier,0.716049,0.716049,0.716049,0.716049,0.713889,0.426725,0.029952
11,Count-Based Classifier,0.728395,0.728395,0.728395,0.728395,0.727778,0.453600,0.019601

# 4. Congressional Voting Records Dataset

In [40]:
# Loading the dataset
df = pd.read_csv("datasets/house-votes-84.csv")

In [41]:
# Displaying the first five records of the dataset
df.head()

,class,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y

In [42]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(435, 17)

In [43]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [44]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

democrat      267
republican    168
Name: class, dtype: int64

In [45]:
# Encoding the attributes of the dataset
df = encoding(df)

In [46]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [47]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [48]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.9        0.91428571 0.87142857 0.89855072 0.85507246] |
|                         |                                                          |
|  Average Accuracy Score |                    0.8878674948240166                    |
|                         |                                                          |
|     Precision Score     | [0.9        0.91428571 0.87142857 0.89855072 0.85507246] |
|                         |                                                          |
| Average Precision Score |                    0.8878674948240166                    |
|                         |                                                          |
|       Recall Score      | [0.9        0.91428571 0.87142857 0.89855072 0.85507246] |
|                         |                                                          |
|   Average Recall Score  |                    0.8878674948240166                    |
|                         |                                                          |
|         F1 Score        | [0.9        0.91428571 0.87142857 0.89855072 0.85507246] |
|                         |                                                          |
|     Average F1 Score    |                    0.8878674948240166                    |
+-------------------------+----------------------------------------------------------+

In [50]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [51]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.942529,0.942529,0.942529,0.942529,0.926555,0.874531,0.005786
1,K-Nearest Neighbours,0.931034,0.931034,0.931034,0.931034,0.924827,0.849654,0.012905
2,Support Vector Machine,0.977011,0.977011,0.977011,0.977011,0.974942,0.949885,0.010747
3,Naive Bayes Classifier,0.896552,0.896552,0.896552,0.896552,0.890841,0.776334,0.006157
4,Logistic Regression,0.988506,0.988506,0.988506,0.988506,0.983871,0.975071,0.006334
5,Multi Layer Perceptron,0.988506,0.988506,0.988506,0.988506,0.983871,0.975071,2.575101
6,AdaBoost Classifier,0.965517,0.965517,0.965517,0.965517,0.951613,0.925904,0.045485
7,Random Forest,0.965517,0.965517,0.965517,0.965517,0.966014,0.925651,0.129999
8,Gradient Boosting,0.965517,0.965517,0.965517,0.965517,0.951613,0.925904,0.063159
9,Extra Trees,0.965517,0.965517,0.965517,0.965517,0.966014,0.925651,0.061922
10,Custom Naive Bayes Classifier,0.896552,0.896552,0.896552,0.896552,0.890841,0.776334,0.054414
11,Count-Based Classifier,0.896552,0.896552,0.896552,0.896552,0.876440,0.771784,0.034148

# 5. Tic-Tac-Toe Endgame Dataset

In [52]:
# Loading the dataset
df = pd.read_csv("datasets/tic-tac-toe.csv")

In [53]:
# Displaying the first five records of the dataset
df.head()

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,class
0,x,x,x,x,o,o,x,o,o,positive
1,x,x,x,x,o,o,o,x,o,positive
2,x,x,x,x,o,o,o,o,x,positive
3,x,x,x,x,o,o,o,b,b,positive
4,x,x,x,x,o,o,b,o,b,positive

In [54]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(958, 10)

In [55]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [56]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

positive    626
negative    332
Name: class, dtype: int64

In [57]:
# Encoding the attributes of the dataset
df = encoding(df)

In [58]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [59]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [60]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [61]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.61691542 0.65       0.65       0.7        0.665     ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.6563830845771145                    |
|                         |                                                          |
|     Precision Score     | [0.61691542 0.65       0.65       0.7        0.665     ] |
|                         |                                                          |
| Average Precision Score |                    0.6563830845771145                    |
|                         |                                                          |
|       Recall Score      | [0.61691542 0.65       0.65       0.7        0.665     ] |
|                         |                                                          |
|   Average Recall Score  |                    0.6563830845771145                    |
|                         |                                                          |
|         F1 Score        | [0.61691542 0.65       0.65       0.7        0.665     ] |
|                         |                                                          |
|     Average F1 Score    |                    0.6563830845771145                    |
+-------------------------+----------------------------------------------------------+

In [63]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [64]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.880478,0.880478,0.880478,0.880478,0.880476,0.760952,0.006208
1,K-Nearest Neighbours,0.836653,0.836653,0.836653,0.836653,0.836349,0.680963,0.014333
2,Support Vector Machine,0.932271,0.932271,0.932271,0.932271,0.932349,0.865248,0.104984
3,Naive Bayes Classifier,0.641434,0.641434,0.641434,0.641434,0.641206,0.284314,0.006005
4,Logistic Regression,0.581673,0.581673,0.581673,0.581673,0.581556,0.163402,0.006389
5,Multi Layer Perceptron,0.776892,0.776892,0.776892,0.776892,0.776921,0.553876,3.004745
6,AdaBoost Classifier,0.689243,0.689243,0.689243,0.689243,0.689175,0.378590,0.061501
7,Random Forest,0.972112,0.972112,0.972112,0.972112,0.972127,0.944254,0.136939
8,Gradient Boosting,0.932271,0.932271,0.932271,0.932271,0.932222,0.864774,0.081120
9,Extra Trees,0.972112,0.972112,0.972112,0.972112,0.972127,0.944254,0.097602
10,Custom Naive Bayes Classifier,0.641434,0.641434,0.641434,0.641434,0.641206,0.284314,0.083451
11,Count-Based Classifier,0.629482,0.629482,0.629482,0.629482,0.629492,0.258984,0.051140

# 6. Nursery Dataset

In [65]:
# Loading the dataset
df = pd.read_csv("datasets/nursery.csv")

In [66]:
# Displaying the first five records of the dataset
df.head()

,parents,has_nurs,form,children,housing,finance,social,health,class
0,usual,proper,complete,1,convenient,convenient,nonprob,recommended,recommend
1,usual,proper,complete,1,convenient,convenient,nonprob,priority,priority
2,usual,proper,complete,1,convenient,convenient,nonprob,not_recom,not_recom
3,usual,proper,complete,1,convenient,convenient,slightly_prob,recommended,recommend
4,usual,proper,complete,1,convenient,convenient,slightly_prob,priority,priority

In [67]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(12960, 9)

In [68]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [69]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

not_recom     4320
priority      4266
spec_prior    4044
very_recom     328
recommend        2
Name: class, dtype: int64

In [70]:
# Removing classes having <= 4 instances
df = remove_class(df,'class')

In [71]:
# Encoding the attributes of the dataset
df = encoding(df)

In [72]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [73]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [74]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.85920926 0.86348288 0.8620357  0.87071877 0.86444766] |
|                         |                                                          |
|  Average Accuracy Score |                    0.8639788510123037                    |
|                         |                                                          |
|     Precision Score     | [0.85920926 0.86348288 0.8620357  0.87071877 0.86444766] |
|                         |                                                          |
| Average Precision Score |                    0.8639788510123037                    |
|                         |                                                          |
|       Recall Score      | [0.85920926 0.86348288 0.8620357  0.87071877 0.86444766] |
|                         |                                                          |
|   Average Recall Score  |                    0.8639788510123037                    |
|                         |                                                          |
|         F1 Score        | [0.85920926 0.86348288 0.8620357  0.87071877 0.86444766] |
|                         |                                                          |
|     Average F1 Score    |                    0.8639788510123037                    |
+-------------------------+----------------------------------------------------------+

In [76]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [77]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.997299,0.997299,0.997299,0.997299,0.996653,0.996041,0.014950
1,K-Nearest Neighbours,0.939043,0.939043,0.939043,0.939043,0.985792,0.910301,0.112116
2,Support Vector Machine,0.951389,0.951389,0.951389,0.951389,0.996052,0.928532,3.208594
3,Naive Bayes Classifier,0.912809,0.912809,0.912809,0.912809,0.986501,0.871808,0.014631
4,Logistic Regression,0.769676,0.769676,0.769676,0.769676,0.920900,0.659953,1.327773
5,Multi Layer Perceptron,0.998843,0.998843,0.998843,0.998843,0.999999,0.998303,6.343425
6,AdaBoost Classifier,0.839120,0.839120,0.839120,0.839120,0.941626,0.773875,0.270245
7,Random Forest,0.984568,0.984568,0.984568,0.984568,0.999394,0.977403,0.369190
8,Gradient Boosting,0.980324,0.980324,0.980324,0.980324,0.999394,0.971168,1.796277
9,Extra Trees,0.976080,0.976080,0.976080,0.976080,0.998147,0.964945,0.420322
10,XGBoost,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.682337
11,Custom Naive Bayes Classifier,0.912809,0.912809,0.912809,0.912809,0.986546,0.871808,1.435715
12,Count-Based Classifier,0.867284,0.867284,0.867284,0.867284,0.976814,0.813511,0.736858

# 7. Soybean (Large) Dataset

In [78]:
# Loading the dataset
df = pd.read_csv("datasets/soybean-large.csv")

In [79]:
# Displaying the first five records of the dataset
df.head()

,class,date,plant-stand,precip,temp,hail,crop-hist,area-damaged,severity,seed-tmt,...,int-discolor,sclerotia,fruit-pods,fruit spots,seed,mold-growth,seed-discolor,seed-size,shriveling,roots
0,diaporthe-stem-canker,6,0,2,1,0,1,1,1,0,...,0,0,0,4,0,0,0,0,0,0
1,diaporthe-stem-canker,4,0,2,1,0,2,0,2,1,...,0,0,0,4,0,0,0,0,0,0
2,diaporthe-stem-canker,3,0,2,1,0,1,0,2,1,...,0,0,0,4,0,0,0,0,0,0
3,diaporthe-stem-canker,3,0,2,1,0,1,0,2,0,...,0,0,0,4,0,0,0,0,0,0
4,diaporthe-stem-canker,6,0,2,1,0,2,0,1,0,...,0,0,0,4,0,0,0,0,0,0

In [80]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(307, 36)

In [81]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [82]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

frog-eye-leaf-spot             40
phytophthora-rot               40
alternarialeaf-spot            40
brown-spot                     40
brown-stem-rot                 20
anthracnose                    20
diaporthe-stem-canker          10
purple-seed-stain              10
phyllosticta-leaf-spot         10
bacterial-pustule              10
charcoal-rot                   10
bacterial-blight               10
downy-mildew                   10
powdery-mildew                 10
rhizoctonia-root-rot           10
diaporthe-pod-&-stem-blight     6
cyst-nematode                   6
herbicide-injury                4
2-4-d-injury                    1
Name: class, dtype: int64

In [83]:
# Removing classes having <= 4 instances
df = remove_class(df,'class')

In [84]:
# Encoding the attributes of the dataset
df = encoding(df)

In [85]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [86]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [87]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [88]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [89]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.72477064 0.75229358 0.71559633 0.74311927 0.69444444] |
|                         |                                                          |
|  Average Accuracy Score |                    0.7260448521916413                    |
|                         |                                                          |
|     Precision Score     | [0.72477064 0.75229358 0.71559633 0.74311927 0.69444444] |
|                         |                                                          |
| Average Precision Score |                    0.7260448521916413                    |
|                         |                                                          |
|       Recall Score      | [0.72477064 0.75229358 0.71559633 0.74311927 0.69444444] |
|                         |                                                          |
|   Average Recall Score  |                    0.7260448521916413                    |
|                         |                                                          |
|         F1 Score        | [0.72477064 0.75229358 0.71559633 0.74311927 0.69444444] |
|                         |                                                          |
|     Average F1 Score    |                    0.7260448521916413                    |
+-------------------------+----------------------------------------------------------+

In [90]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [91]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.941176,0.941176,0.941176,0.941176,0.969469,0.937692,0.009047
1,K-Nearest Neighbours,0.948529,0.948529,0.948529,0.948529,0.995393,0.945221,0.016047
2,Support Vector Machine,0.970588,0.970588,0.970588,0.970588,0.998667,0.968786,0.065676
3,Naive Bayes Classifier,0.955882,0.955882,0.955882,0.955882,0.998555,0.952987,0.013018
4,Logistic Regression,0.933824,0.933824,0.933824,0.933824,0.998965,0.929888,1.053269
5,Multi Layer Perceptron,0.948529,0.948529,0.948529,0.948529,0.998962,0.945673,9.204938
6,AdaBoost Classifier,0.308824,0.308824,0.308824,0.308824,0.800248,0.360970,0.091528
7,Random Forest,0.985294,0.985294,0.985294,0.985294,0.999546,0.984279,0.118073
8,Gradient Boosting,0.970588,0.970588,0.970588,0.970588,0.999289,0.969117,1.296581
9,Extra Trees,0.977941,0.977941,0.977941,0.977941,0.999341,0.976477,0.079285
10,XGBoost,0.955882,0.955882,0.955882,0.955882,0.998463,0.953265,0.487606
11,Custom Naive Bayes Classifier,0.963235,0.963235,0.963235,0.963235,0.998555,0.960749,1.205531
12,Count-Based Classifier,0.617647,0.617647,0.617647,0.617647,0.993165,0.616830,0.772475

# 8. Molecular Biology (Promoter Gene Sequences) Dataset

In [92]:
# Loading the dataset
df = pd.read_csv("datasets/promoters.csv")

In [93]:
# Displaying the first five records of the dataset
df.head()

  class instance_name                                           sequence
0     +           S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +          AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +          AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +         DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +     LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...

In [94]:
# Formatting columns to create a proper dataset
df['sequence'] = df['sequence'].apply(lambda x: x.replace('\t',''))
attributes = [str(i) for i in range(0,59)]
df[attributes] = df['sequence'].str.split(pat='', expand=True)
df.drop(['sequence','0','58'],axis=1,inplace=True)

In [95]:
# Displaying the first five records of the dataset
df.head()

,class,instance_name,1,2,3,4,5,6,7,8,...,48,49,50,51,52,53,54,55,56,57
0,+,S10,t,a,c,t,a,g,c,a,...,g,g,c,t,t,g,t,c,g,t
1,+,AMPC,t,g,c,t,a,t,c,c,...,g,c,a,t,c,g,c,c,a,a
2,+,AROH,g,t,a,c,t,a,g,a,...,c,c,a,c,c,c,g,g,c,g
3,+,DEOP2,a,a,t,t,g,t,g,a,...,t,a,a,c,a,a,a,c,t,c
4,+,LEU1_TRNA,t,c,g,a,t,a,a,t,...,t,c,c,g,t,g,g,t,a,g

In [96]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(106, 59)

In [97]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [98]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

+    53
-    53
Name: class, dtype: int64

In [99]:
# Encoding the attributes of the dataset
df = encoding(df)

In [100]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [101]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [102]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [103]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.64705882 0.64705882 1.         0.88235294 0.75      ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.7852941176470588                    |
|                         |                                                          |
|     Precision Score     | [0.64705882 0.64705882 1.         0.88235294 0.75      ] |
|                         |                                                          |
| Average Precision Score |                    0.7852941176470588                    |
|                         |                                                          |
|       Recall Score      | [0.64705882 0.64705882 1.         0.88235294 0.75      ] |
|                         |                                                          |
|   Average Recall Score  |                    0.7852941176470588                    |
|                         |                                                          |
|         F1 Score        | [0.64705882 0.64705882 1.         0.88235294 0.75      ] |
|                         |                                                          |
|     Average F1 Score    |                    0.7852941176470588                    |
+-------------------------+----------------------------------------------------------+

In [104]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [105]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.005696
1,K-Nearest Neighbours,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.012119
2,Support Vector Machine,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.006252
3,Naive Bayes Classifier,0.909091,0.909091,0.909091,0.909091,0.909091,0.832050,0.006836
4,Logistic Regression,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.012099
5,Multi Layer Perceptron,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.435810
6,AdaBoost Classifier,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.005021
7,Random Forest,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.091649
8,Gradient Boosting,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.051787
9,Extra Trees,0.954545,0.954545,0.954545,0.954545,0.954545,0.912871,0.083699
10,Custom Naive Bayes Classifier,0.909091,0.909091,0.909091,0.909091,0.909091,0.832050,0.054243
11,Count-Based Classifier,0.772727,0.772727,0.772727,0.772727,0.772727,0.612372,0.036119

# 9. Balance Scale Dataset

In [106]:
# Loading the dataset
df = pd.read_csv("datasets/balance-scale.csv")

In [107]:
# Displaying the first five records of the dataset
df.head()

  class  left-weight  left-distance  right-weight  right-distance
0     B            1              1             1               1
1     R            1              1             1               2
2     R            1              1             1               3
3     R            1              1             1               4
4     R            1              1             1               5

In [108]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(625, 5)

In [109]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [110]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

R    288
L    288
B     49
Name: class, dtype: int64

In [111]:
# Encoding the attributes of the dataset
df = encoding(df)

In [112]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [113]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [114]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------+
|    Evaluation Metric    |           Value            |
+-------------------------+----------------------------+
|      Accuracy Score     | [0.9  0.88 0.92 0.89 0.91] |
|                         |                            |
|  Average Accuracy Score |            0.9             |
|                         |                            |
|     Precision Score     | [0.9  0.88 0.92 0.89 0.91] |
|                         |                            |
| Average Precision Score |            0.9             |
|                         |                            |
|       Recall Score      | [0.9  0.88 0.92 0.89 0.91] |
|                         |                            |
|   Average Recall Score  |            0.9             |
|                         |                            |
|         F1 Score        | [0.9  0.88 0.92 0.89 0.91] |
|                         |                            |
|     Average F1 Score    |            0.9             |
+-------------------------+----------------------------+

In [116]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [117]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.768,0.768,0.768,0.768,0.723431,0.604870,0.006417
1,K-Nearest Neighbours,0.816,0.816,0.816,0.816,0.820842,0.682363,0.009116
2,Support Vector Machine,0.904,0.904,0.904,0.904,0.951278,0.835157,0.019702
3,Naive Bayes Classifier,0.896,0.896,0.896,0.896,0.842315,0.820935,0.005745
4,Logistic Regression,0.840,0.840,0.840,0.840,0.954595,0.733634,0.007524
5,Multi Layer Perceptron,0.968,0.968,0.968,0.968,0.997608,0.944901,0.524006
6,AdaBoost Classifier,0.936,0.936,0.936,0.936,0.858374,0.899371,0.037156
7,Random Forest,0.824,0.824,0.824,0.824,0.809350,0.691677,0.072913
8,Gradient Boosting,0.888,0.888,0.888,0.888,0.903488,0.802793,0.120580
9,Extra Trees,0.792,0.792,0.792,0.792,0.758562,0.638453,0.062492
10,XGBoost,0.832,0.832,0.832,0.832,0.924211,0.709954,0.211997
11,Custom Naive Bayes Classifier,0.896,0.896,0.896,0.896,0.842315,0.820935,0.032794
12,Count-Based Classifier,0.896,0.896,0.896,0.896,0.718512,0.819770,0.021410

# 10. Lenses Dataset

In [118]:
# Loading the dataset
df = pd.read_csv("datasets/lenses.csv", delimiter="  ", engine="python")

In [119]:
# Displaying the first five records of the dataset
df.head()

   class  age  spectacle_prescription  astigmatic  tear_production_rate
1      1    1                       1           1                   3.0
2      1    1                       1           2                   2.0
3      1    1                       2           1                   3.0
4      1    1                       2           2                   1.0
5      1    2                       1           1                   3.0

In [120]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(24, 5)

In [121]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [122]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

1    15
2     9
Name: class, dtype: int64

In [123]:
# Encoding the attributes of the dataset
df = encoding(df)

In [124]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [125]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [126]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [127]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------+
|    Evaluation Metric    |           Value            |
+-------------------------+----------------------------+
|      Accuracy Score     | [0.25 0.75 0.5  0.75 1.  ] |
|                         |                            |
|  Average Accuracy Score |            0.65            |
|                         |                            |
|     Precision Score     | [0.25 0.75 0.5  0.75 1.  ] |
|                         |                            |
| Average Precision Score |            0.65            |
|                         |                            |
|       Recall Score      | [0.25 0.75 0.5  0.75 1.  ] |
|                         |                            |
|   Average Recall Score  |            0.65            |
|                         |                            |
|         F1 Score        | [0.25 0.75 0.5  0.75 1.  ] |
|                         |                            |
|     Average F1 Score    |            0.65            |
+-------------------------+----------------------------+

In [128]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [129]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.4,0.4,0.4,0.4,0.25,-0.408248,0.005988
1,K-Nearest Neighbours,0.4,0.4,0.4,0.4,0.25,-0.408248,0.005268
2,Support Vector Machine,0.4,0.4,0.4,0.4,0.25,-0.408248,0.004725
3,Naive Bayes Classifier,0.4,0.4,0.4,0.4,0.25,-0.408248,0.004654
4,Logistic Regression,0.4,0.4,0.4,0.4,0.25,-0.408248,0.005383
5,Multi Layer Perceptron,0.4,0.4,0.4,0.4,0.25,-0.408248,0.083957
6,AdaBoost Classifier,0.4,0.4,0.4,0.4,0.25,-0.408248,0.032844
7,Random Forest,0.4,0.4,0.4,0.4,0.25,-0.408248,0.060809
8,Gradient Boosting,0.4,0.4,0.4,0.4,0.25,-0.408248,0.022415
9,Extra Trees,0.4,0.4,0.4,0.4,0.25,-0.408248,0.044170
10,Custom Naive Bayes Classifier,0.4,0.4,0.4,0.4,0.25,-0.408248,0.005222
11,Count-Based Classifier,0.4,0.4,0.4,0.4,0.25,-0.408248,0.004439

# 11. Molecular Biology (Splice-junction Gene Sequences) Dataset

In [130]:
# Loading the dataset
df = pd.read_csv("datasets/splice.csv")

In [131]:
# Displaying the first five records of the dataset
df.head()

,class,instance_name,sequence
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...

In [132]:
# Formatting columns to create a proper dataset
df['sequence'] = df['sequence'].apply(lambda x: x.replace(' ',''))
attributes = [str(i) for i in range(0,62)]
df[attributes] = df['sequence'].str.split(pat='', expand=True)
df.drop(['sequence','0','61'],axis=1,inplace=True)

In [133]:
# Dropping unwanted columns
df.drop(['instance_name'], axis=1, inplace=True)

In [134]:
# Displaying the first five records of the dataset
df.head()

  class  1  2  3  4  5  6  7  8  9  ... 51 52 53 54 55 56 57 58 59 60
0    EI  C  C  A  G  C  T  G  C  A  ...  A  G  C  C  A  G  T  C  T  G
1    EI  A  G  A  C  C  C  G  C  C  ...  G  T  G  C  C  C  C  C  G  C
2    EI  G  A  G  G  T  G  A  A  G  ...  C  A  C  G  G  G  G  A  T  G
3    EI  G  G  G  C  T  G  C  G  T  ...  G  G  T  T  T  T  C  C  C  C
4    EI  G  C  T  C  A  G  C  C  C  ...  C  C  T  T  G  A  C  C  C  T

[5 rows x 61 columns]

In [135]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(3190, 61)

In [136]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [137]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

N     1655
IE     768
EI     767
Name: class, dtype: int64

In [138]:
# Encoding the attributes of the dataset
df = encoding(df)

In [139]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [140]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [141]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [142]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [143]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.74591195 0.76100629 0.76196474 0.75692695 0.76700252] |
|                         |                                                          |
|  Average Accuracy Score |                    0.7585624891085658                    |
|                         |                                                          |
|     Precision Score     | [0.74591195 0.76100629 0.76196474 0.75692695 0.76700252] |
|                         |                                                          |
| Average Precision Score |                    0.7585624891085658                    |
|                         |                                                          |
|       Recall Score      | [0.74591195 0.76100629 0.76196474 0.75692695 0.76700252] |
|                         |                                                          |
|   Average Recall Score  |                    0.7585624891085658                    |
|                         |                                                          |
|         F1 Score        | [0.74591195 0.76100629 0.76196474 0.75692695 0.76700252] |
|                         |                                                          |
|     Average F1 Score    |                    0.7585624891085658                    |
+-------------------------+----------------------------------------------------------+

In [144]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [145]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.931521,0.931521,0.931521,0.931521,0.948549,0.897353,0.034708
1,K-Nearest Neighbours,0.752266,0.752266,0.752266,0.752266,0.929266,0.659889,0.049720
2,Support Vector Machine,0.915408,0.915408,0.915408,0.915408,0.982004,0.873357,2.815112
3,Naive Bayes Classifier,0.960725,0.960725,0.960725,0.960725,0.996277,0.941158,0.014964
4,Logistic Regression,0.883182,0.883182,0.883182,0.883182,0.963496,0.825586,1.511281
5,Multi Layer Perceptron,0.916415,0.916415,0.916415,0.916415,0.983168,0.875119,25.243046
6,AdaBoost Classifier,0.934542,0.934542,0.934542,0.934542,0.969878,0.902349,0.354125
7,Random Forest,0.963746,0.963746,0.963746,0.963746,0.996372,0.945847,0.396188
8,Gradient Boosting,0.975831,0.975831,0.975831,0.975831,0.997707,0.963953,3.137667
9,Extra Trees,0.975831,0.975831,0.975831,0.975831,0.997681,0.963764,0.412126
10,XGBoost,0.977845,0.977845,0.977845,0.977845,0.997492,0.966919,1.003208
11,Custom Naive Bayes Classifier,0.960725,0.960725,0.960725,0.960725,0.996277,0.941158,3.153711
12,Count-Based Classifier,0.761329,0.761329,0.761329,0.761329,0.984441,0.681472,1.599840

# 12. SPECT Heart Dataset

In [146]:
# Loading the dataset
df = pd.read_csv("datasets/SPECT.csv")

In [147]:
# Displaying the first five records of the dataset
df.head()

,class,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,F22
0,1,0,0,0,1,0,0,0,1,1,...,1,1,0,0,0,0,0,0,0,0
1,1,0,0,1,1,0,0,0,1,1,...,1,1,0,0,0,0,0,0,0,1
2,1,1,0,1,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
4,1,0,0,0,0,0,0,0,1,0,...,1,0,1,1,0,0,0,0,0,0

In [148]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(267, 23)

In [149]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [150]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

1    212
0     55
Name: class, dtype: int64

In [151]:
# Encoding the attributes of the dataset
df = encoding(df)

In [152]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [153]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [154]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [155]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.79069767 0.79069767 0.76744186 0.78571429 0.78571429] |
|                         |                                                          |
|  Average Accuracy Score |                    0.7840531561461793                    |
|                         |                                                          |
|     Precision Score     | [0.79069767 0.79069767 0.76744186 0.78571429 0.78571429] |
|                         |                                                          |
| Average Precision Score |                    0.7840531561461793                    |
|                         |                                                          |
|       Recall Score      | [0.79069767 0.79069767 0.76744186 0.78571429 0.78571429] |
|                         |                                                          |
|   Average Recall Score  |                    0.7840531561461793                    |
|                         |                                                          |
|         F1 Score        | [0.79069767 0.79069767 0.76744186 0.78571429 0.78571429] |
|                         |                                                          |
|     Average F1 Score    |                    0.7840531561461793                    |
+-------------------------+----------------------------------------------------------+

In [156]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [157]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.703704,0.703704,0.703704,0.703704,0.600000,0.166410,0.006267
1,K-Nearest Neighbours,0.722222,0.722222,0.722222,0.722222,0.611111,0.188982,0.010454
2,Support Vector Machine,0.740741,0.740741,0.740741,0.740741,0.533333,0.066667,0.009333
3,Naive Bayes Classifier,0.777778,0.777778,0.777778,0.777778,0.777778,0.445789,0.006019
4,Logistic Regression,0.759259,0.759259,0.759259,0.759259,0.544444,0.093250,0.006342
5,Multi Layer Perceptron,0.796296,0.796296,0.796296,0.796296,0.566667,0.158114,2.978002
6,AdaBoost Classifier,0.759259,0.759259,0.759259,0.759259,0.588889,0.170561,0.067228
7,Random Forest,0.777778,0.777778,0.777778,0.777778,0.600000,0.200000,0.124848
8,Gradient Boosting,0.777778,0.777778,0.777778,0.777778,0.555556,0.123278,0.065339
9,Extra Trees,0.759259,0.759259,0.759259,0.759259,0.588889,0.170561,0.062490
10,Custom Naive Bayes Classifier,0.777778,0.777778,0.777778,0.777778,0.777778,0.445789,0.047924
11,Count-Based Classifier,0.833333,0.833333,0.833333,0.833333,0.500000,0.000000,0.032840

# 13. Primary Tumor Dataset

In [158]:
# Loading the dataset
df = pd.read_csv("datasets/primary-tumor.csv")

In [159]:
# Displaying the first five records of the dataset
df.head()

,class,age,sex,histologic-type,degree-of-diffe,bone,bone-marrow,lung,pleura,peritoneum,liver,brain,skin,neck,supraclavicular,axillar,mediastinum,abdominal
0,1,1,1,?,3,2,2,1,2,2,2,2,2,2,2,2,2,2
1,1,1,1,?,3,2,2,2,2,2,1,2,2,2,1,2,1,2
2,1,1,2,2,3,1,2,2,2,2,2,2,2,2,2,2,1,2
3,1,1,2,?,3,1,2,1,1,2,2,2,2,2,2,2,1,2
4,1,1,2,?,3,1,2,1,1,2,2,2,2,2,2,2,1,2

In [160]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(339, 18)

In [161]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [162]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

1     84
5     39
18    29
11    28
14    24
22    24
2     20
12    16
7     14
4     14
17    10
3      9
13     7
8      6
19     6
10     2
15     2
20     2
6      1
16     1
21     1
Name: class, dtype: int64

In [163]:
# Removing classes having <= 4 instances
df = remove_class(df,'class')

In [164]:
# Encoding the attributes of the dataset
df = encoding(df)

In [165]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [166]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [167]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [168]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [169]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.65346535 0.64356436 0.5990099  0.64676617 0.5920398 ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.6269691148219299                    |
|                         |                                                          |
|     Precision Score     | [0.65346535 0.64356436 0.5990099  0.64676617 0.5920398 ] |
|                         |                                                          |
| Average Precision Score |                    0.6269691148219299                    |
|                         |                                                          |
|       Recall Score      | [0.65346535 0.64356436 0.5990099  0.64676617 0.5920398 ] |
|                         |                                                          |
|   Average Recall Score  |                    0.6269691148219299                    |
|                         |                                                          |
|         F1 Score        | [0.65346535 0.64356436 0.5990099  0.64676617 0.5920398 ] |
|                         |                                                          |
|     Average F1 Score    |                    0.6269691148219299                    |
+-------------------------+----------------------------------------------------------+

In [170]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [171]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.821429,0.821429,0.821429,0.821429,0.921847,0.810123,0.009269
1,K-Nearest Neighbours,0.833333,0.833333,0.833333,0.833333,0.951261,0.823407,0.018688
2,Support Vector Machine,0.837302,0.837302,0.837302,0.837302,0.979870,0.827132,0.104119
3,Naive Bayes Classifier,0.789683,0.789683,0.789683,0.789683,0.967638,0.776820,0.011882
4,Logistic Regression,0.793651,0.793651,0.793651,0.793651,0.971717,0.780512,0.105085
5,Multi Layer Perceptron,0.829365,0.829365,0.829365,0.829365,0.977589,0.818090,19.728841
6,AdaBoost Classifier,0.305556,0.305556,0.305556,0.305556,0.742822,0.286106,0.127020
7,Random Forest,0.841270,0.841270,0.841270,0.841270,0.977321,0.830820,0.156564
8,Gradient Boosting,0.821429,0.821429,0.821429,0.821429,0.973988,0.809858,1.169230
9,Extra Trees,0.833333,0.833333,0.833333,0.833333,0.963524,0.822072,0.097460
10,XGBoost,0.829365,0.829365,0.829365,0.829365,0.978245,0.817917,1.073992
11,Custom Naive Bayes Classifier,0.785714,0.785714,0.785714,0.785714,0.967656,0.772327,1.241902
12,Count-Based Classifier,0.626984,0.626984,0.626984,0.626984,0.941365,0.610555,0.619589

# 14. Chess (King-Rook vs. King-Pawn) Dataset

In [172]:
# Loading the dataset
df = pd.read_csv("datasets/kr-vs-kp.csv")

In [173]:
# Displaying the first five records of the dataset
df.head()

,bkblk,bknwy,bkon8,bkona,bkspr,bkxbq,bkxcr,bkxwp,blxwp,bxqsq,...,spcop,stlmt,thrsk,wkcti,wkna8,wknck,wkovl,wkpos,wtoeg,class
0,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
1,f,f,f,f,t,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
2,f,f,f,f,t,f,t,f,f,f,...,f,f,f,f,f,f,t,t,n,won
3,f,f,f,f,f,f,f,f,t,f,...,f,f,f,f,f,f,t,t,n,won
4,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won

In [174]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(3196, 37)

In [175]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [176]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

won      1669
nowin    1527
Name: class, dtype: int64

In [177]:
# Encoding the attributes of the dataset
df = encoding(df)

In [178]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [179]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [180]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [181]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [182]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.83333333 0.82209738 0.82209738 0.83707865 0.83895131] |
|                         |                                                          |
|  Average Accuracy Score |                    0.8307116104868915                    |
|                         |                                                          |
|     Precision Score     | [0.83333333 0.82209738 0.82209738 0.83707865 0.83895131] |
|                         |                                                          |
| Average Precision Score |                    0.8307116104868915                    |
|                         |                                                          |
|       Recall Score      | [0.83333333 0.82209738 0.82209738 0.83707865 0.83895131] |
|                         |                                                          |
|   Average Recall Score  |                    0.8307116104868915                    |
|                         |                                                          |
|         F1 Score        | [0.83333333 0.82209738 0.82209738 0.83707865 0.83895131] |
|                         |                                                          |
|     Average F1 Score    |                    0.8307116104868915                    |
+-------------------------+----------------------------------------------------------+

In [183]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [184]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.995509,0.995509,0.995509,0.995509,0.995476,0.991018,0.011579
1,K-Nearest Neighbours,0.961078,0.961078,0.961078,0.961078,0.960810,0.922347,0.036311
2,Support Vector Machine,0.964072,0.964072,0.964072,0.964072,0.964182,0.928197,0.675527
3,Naive Bayes Classifier,0.868263,0.868263,0.868263,0.868263,0.868519,0.736907,0.009587
4,Logistic Regression,0.950599,0.950599,0.950599,0.950599,0.950734,0.901286,0.041278
5,Multi Layer Perceptron,0.994012,0.994012,0.994012,0.994012,0.993947,0.988035,15.628510
6,AdaBoost Classifier,0.962575,0.962575,0.962575,0.962575,0.962590,0.925126,0.161966
7,Random Forest,0.983533,0.983533,0.983533,0.983533,0.983369,0.967150,0.194284
8,Gradient Boosting,0.976048,0.976048,0.976048,0.976048,0.976414,0.952726,0.211270
9,Extra Trees,0.989521,0.989521,0.989521,0.989521,0.989422,0.979068,0.167671
10,Custom Naive Bayes Classifier,0.868263,0.868263,0.868263,0.868263,0.868519,0.736907,0.951574
11,Count-Based Classifier,0.836826,0.836826,0.836826,0.836826,0.837351,0.674990,0.477001

# 15. Lymphography Dataset

In [185]:
# Loading the dataset
df = pd.read_csv("datasets/lymphography.csv")

In [186]:
# Displaying the first five records of the dataset
df.head()

,class,lymphatics,block of affere,bl. of lymph. c,bl. of lymph. s,by pass,extravasates,regeneration of,early uptake in,lym.nodes dimin,lym.nodes enlar,changes in lym.,defect in node,changes in node,changes in stru,special forms,dislocation of,exclusion of no,no. of nodes in
0,3,4,2,1,1,1,1,1,2,1,2,2,2,4,8,1,1,2,2
1,2,3,2,1,1,2,2,1,2,1,3,3,2,3,4,2,2,2,2
2,3,3,2,2,2,2,2,2,2,1,4,3,3,4,8,3,2,2,7
3,3,3,1,1,1,1,2,1,2,1,3,3,4,4,4,3,1,2,6
4,2,3,1,1,1,1,1,1,1,1,2,2,4,3,5,1,2,2,1

In [187]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(148, 19)

In [188]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [189]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

2    81
3    61
4     4
1     2
Name: class, dtype: int64

In [190]:
# Removing classes having <= 4 instances
df = remove_class(df,'class')

In [191]:
# Encoding the attributes of the dataset
df = encoding(df)

In [192]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [193]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [194]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [195]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [196]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.84615385 0.84615385 0.84615385 0.84615385 0.88      ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.852923076923077                     |
|                         |                                                          |
|     Precision Score     | [0.84615385 0.84615385 0.84615385 0.84615385 0.88      ] |
|                         |                                                          |
| Average Precision Score |                    0.852923076923077                     |
|                         |                                                          |
|       Recall Score      | [0.84615385 0.84615385 0.84615385 0.84615385 0.88      ] |
|                         |                                                          |
|   Average Recall Score  |                    0.852923076923077                     |
|                         |                                                          |
|         F1 Score        | [0.84615385 0.84615385 0.84615385 0.84615385 0.88      ] |
|                         |                                                          |
|     Average F1 Score    |                    0.852923076923077                     |
+-------------------------+----------------------------------------------------------+

In [197]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [198]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.818182,0.818182,0.818182,0.818182,0.818015,0.636029,0.006963
1,K-Nearest Neighbours,0.818182,0.818182,0.818182,0.818182,0.821691,0.658062,0.011418
2,Support Vector Machine,0.909091,0.909091,0.909091,0.909091,0.908088,0.819194,0.007674
3,Naive Bayes Classifier,0.848485,0.848485,0.848485,0.848485,0.847426,0.697422,0.006277
4,Logistic Regression,0.848485,0.848485,0.848485,0.848485,0.851103,0.710081,0.008137
5,Multi Layer Perceptron,0.848485,0.848485,0.848485,0.848485,0.851103,0.710081,1.656233
6,AdaBoost Classifier,0.848485,0.848485,0.848485,0.848485,0.851103,0.710081,0.077029
7,Random Forest,0.878788,0.878788,0.878788,0.878788,0.878676,0.757353,0.122379
8,Gradient Boosting,0.848485,0.848485,0.848485,0.848485,0.847426,0.697422,0.061733
9,Extra Trees,0.939394,0.939394,0.939394,0.939394,0.941176,0.885615,0.063000
10,Custom Naive Bayes Classifier,0.848485,0.848485,0.848485,0.848485,0.847426,0.697422,0.027102
11,Count-Based Classifier,0.878788,0.878788,0.878788,0.878788,0.882353,0.782154,0.020184

# 16. Connect-4 Dataset

In [199]:
# Loading the dataset
df = pd.read_csv("datasets/connect-4.csv")

In [200]:
# Displaying the first five records of the dataset
df.head()

  a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f4 f5 f6 g1 g2 g3 g4 g5 g6 class
0  b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
1  b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
2  b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
3  b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
4  o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win

[5 rows x 43 columns]

In [201]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(67557, 43)

In [202]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [203]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

win     44473
loss    16635
draw     6449
Name: class, dtype: int64

In [204]:
# Encoding the attributes of the dataset
df = encoding(df)

In [205]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [206]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [207]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [208]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [209]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.40970628 0.40773879 0.41663934 0.41181431 0.41401602] |
|                         |                                                          |
|  Average Accuracy Score |                   0.41198294842366606                    |
|                         |                                                          |
|     Precision Score     | [0.40970628 0.40773879 0.41663934 0.41181431 0.41401602] |
|                         |                                                          |
| Average Precision Score |                   0.41198294842366606                    |
|                         |                                                          |
|       Recall Score      | [0.40970628 0.40773879 0.41663934 0.41181431 0.41401602] |
|                         |                                                          |
|   Average Recall Score  |                   0.41198294842366606                    |
|                         |                                                          |
|         F1 Score        | [0.40970628 0.40773879 0.41663934 0.41181431 0.41401602] |
|                         |                                                          |
|     Average F1 Score    |                   0.41198294842366606                    |
+-------------------------+----------------------------------------------------------+

In [210]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [211]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.869772,0.869772,0.869772,0.869772,0.907020,0.805132,0.590363
1,K-Nearest Neighbours,0.813596,0.813596,0.813596,0.813596,0.934389,0.725884,12.495159
2,Support Vector Machine,0.798344,0.798344,0.798344,0.798344,0.930930,0.699792,5080.413919
3,Naive Bayes Classifier,0.576001,0.576001,0.576001,0.576001,0.760903,0.366309,0.166798
4,Logistic Regression,0.585407,0.585407,0.585407,0.585407,0.754996,0.390099,5.957296
5,Multi Layer Perceptron,0.808574,0.808574,0.808574,0.808574,0.937326,0.713423,303.483117
6,AdaBoost Classifier,0.615537,0.615537,0.615537,0.615537,0.791586,0.427318,2.693930
7,Random Forest,0.910171,0.910171,0.910171,0.910171,0.983644,0.865261,6.565204
8,Gradient Boosting,0.689589,0.689589,0.689589,0.689589,0.854350,0.535127,24.248902
9,Extra Trees,0.911707,0.911707,0.911707,0.911707,0.984094,0.867792,8.221933
10,XGBoost,0.845713,0.845713,0.845713,0.845713,0.955862,0.769221,13.667049
11,Custom Naive Bayes Classifier,0.576001,0.576001,0.576001,0.576001,0.760903,0.366309,47.241061
12,Count-Based Classifier,0.405636,0.405636,0.405636,0.405636,0.711576,0.160182,26.068109

# 17. Hayes-Roth Dataset

In [212]:
# Loading the dataset
df = pd.read_csv("datasets/hayes-roth.csv")

In [213]:
# Displaying the first five records of the dataset
df.head()

   hobby  age  educational_level  marital_status  class
0      2    1                  1               2      1
1      2    1                  3               2      2
2      3    1                  4               1      3
3      2    4                  2               2      3
4      1    1                  3               4      3

In [214]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(160, 5)

In [215]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [216]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

1    65
2    64
3    31
Name: class, dtype: int64

In [217]:
# Encoding the attributes of the dataset
df = encoding(df)

In [218]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [219]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [220]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [221]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.53846154 0.57692308 0.69230769 0.76       0.64      ] |
|                         |                                                          |
|  Average Accuracy Score |                    0.6415384615384616                    |
|                         |                                                          |
|     Precision Score     | [0.53846154 0.57692308 0.69230769 0.76       0.64      ] |
|                         |                                                          |
| Average Precision Score |                    0.6415384615384616                    |
|                         |                                                          |
|       Recall Score      | [0.53846154 0.57692308 0.69230769 0.76       0.64      ] |
|                         |                                                          |
|   Average Recall Score  |                    0.6415384615384616                    |
|                         |                                                          |
|         F1 Score        | [0.53846154 0.57692308 0.69230769 0.76       0.64      ] |
|                         |                                                          |
|     Average F1 Score    |                    0.6415384615384616                    |
+-------------------------+----------------------------------------------------------+

In [222]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [223]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.87500,0.87500,0.87500,0.87500,0.945703,0.797468,0.006200
1,K-Nearest Neighbours,0.68750,0.68750,0.68750,0.68750,0.772004,0.484761,0.006631
2,Support Vector Machine,0.81250,0.81250,0.81250,0.81250,0.875462,0.729003,0.008701
3,Naive Bayes Classifier,0.84375,0.84375,0.84375,0.84375,0.966276,0.767773,0.005091
4,Logistic Regression,0.40625,0.40625,0.40625,0.40625,0.689999,0.039171,0.005891
5,Multi Layer Perceptron,0.75000,0.75000,0.75000,0.75000,0.937346,0.596097,0.177201
6,AdaBoost Classifier,0.50000,0.50000,0.50000,0.50000,0.774621,0.486427,0.031232
7,Random Forest,0.84375,0.84375,0.84375,0.84375,0.938767,0.764506,0.073855
8,Gradient Boosting,0.84375,0.84375,0.84375,0.84375,0.976054,0.764506,0.076781
9,Extra Trees,0.84375,0.84375,0.84375,0.84375,0.930954,0.750416,0.060683
10,XGBoost,0.81250,0.81250,0.81250,0.81250,0.961518,0.707742,0.049146
11,Custom Naive Bayes Classifier,0.84375,0.84375,0.84375,0.84375,0.966276,0.767773,0.010821
12,Count-Based Classifier,0.65625,0.65625,0.65625,0.65625,0.930267,0.474855,0.008835

# 18. Lung Cancer Prediction Dataset

In [224]:
# Loading the dataset
df = pd.read_csv("datasets/cancer-patients.csv")

In [225]:
# Displaying the first five records of the dataset
df.head()

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High

In [226]:
# Dropping unwanted columns
df.drop(['index','Patient Id','Age'], axis=1, inplace=True)

In [227]:
# Displaying the first five records of the dataset
df.head()

,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,Smoking,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,1,2,4,5,4,3,2,2,4,3,...,3,4,2,2,3,1,2,3,4,Low
1,1,3,1,5,3,4,2,2,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,1,4,5,6,5,5,4,6,7,2,...,8,7,9,2,1,4,6,7,2,High
3,1,7,7,7,7,6,7,7,7,7,...,4,2,3,1,4,5,6,7,5,High
4,1,6,8,7,7,7,6,7,7,8,...,3,2,4,1,4,2,4,2,3,High

In [228]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(1000, 23)

In [229]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [230]:
# Checking the instance counts of the target attribute
df['Level'].value_counts()

High      365
Medium    332
Low       303
Name: Level, dtype: int64

In [231]:
# Encoding the attributes of the dataset
df = encoding(df)

In [232]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [233]:
# Separating dependent and independent variables
X, y = separating(df, 'Level')

In [234]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [235]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+-------------------------------------------+
|    Evaluation Metric    |                   Value                   |
+-------------------------+-------------------------------------------+
|      Accuracy Score     | [0.9     0.93125 0.9125  0.925   0.91875] |
|                         |                                           |
|  Average Accuracy Score |             0.9175000000000001            |
|                         |                                           |
|     Precision Score     | [0.9     0.93125 0.9125  0.925   0.91875] |
|                         |                                           |
| Average Precision Score |             0.9175000000000001            |
|                         |                                           |
|       Recall Score      | [0.9     0.93125 0.9125  0.925   0.91875] |
|                         |                                           |
|   Average Recall Score  |             0.9175000000000001            |
|                         |                                           |
|         F1 Score        | [0.9     0.93125 0.9125  0.925   0.91875] |
|                         |                                           |
|     Average F1 Score    |             0.9175000000000001            |
+-------------------------+-------------------------------------------+

In [236]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

In [237]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,1.000,1.000,1.000,1.000,1.000000,1.000000,0.004969
1,K-Nearest Neighbours,1.000,1.000,1.000,1.000,1.000000,1.000000,0.016381
2,Support Vector Machine,1.000,1.000,1.000,1.000,1.000000,1.000000,0.019320
3,Naive Bayes Classifier,1.000,1.000,1.000,1.000,1.000000,1.000000,0.005570
4,Logistic Regression,1.000,1.000,1.000,1.000,1.000000,1.000000,0.046024
5,Multi Layer Perceptron,1.000,1.000,1.000,1.000,1.000000,1.000000,1.200656
6,AdaBoost Classifier,0.725,0.725,0.725,0.725,0.870769,0.658113,0.103127
7,Random Forest,1.000,1.000,1.000,1.000,1.000000,1.000000,0.128057
8,Gradient Boosting,1.000,1.000,1.000,1.000,1.000000,1.000000,0.350938
9,Extra Trees,1.000,1.000,1.000,1.000,1.000000,1.000000,0.064043
10,XGBoost,1.000,1.000,1.000,1.000,1.000000,1.000000,0.059970
11,Custom Naive Bayes Classifier,1.000,1.000,1.000,1.000,1.000000,1.000000,0.267027
12,Count-Based Classifier,0.930,0.930,0.930,0.930,0.985888,0.897260,0.150099

# 19. Phishing Website Dataset

In [238]:
# Loading the dataset
df = pd.read_csv("datasets/phishing.csv")

In [239]:
# Displaying the first five records of the dataset
df.head()

,Index,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
0,0,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
1,1,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
2,2,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
3,3,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
4,4,-1,0,-1,1,-1,-1,1,1,-1,...,1,1,1,1,1,-1,1,-1,-1,1

In [240]:
# Dropping unwanted columns
df.drop(['Index'], axis=1, inplace=True)

In [241]:
# Displaying the first five records of the dataset
df.head()

,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,Favicon,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
0,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
1,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
2,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
3,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1
4,-1,0,-1,1,-1,-1,1,1,-1,1,...,1,1,1,1,1,-1,1,-1,-1,1

In [242]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(11054, 31)

In [243]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [244]:
# Checking the instance counts of the target attribute
df['class'].value_counts()

 1    6157
-1    4897
Name: class, dtype: int64

In [245]:
# Encoding the attributes of the dataset
df = encoding(df)

In [246]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [247]:
# Separating dependent and independent variables
X, y = separating(df, 'class')

In [248]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [249]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [250]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.90258752 0.9213198  0.90659898 0.89238579 0.90761421] |
|                         |                                                          |
|  Average Accuracy Score |                    0.9061012601503527                    |
|                         |                                                          |
|     Precision Score     | [0.90258752 0.9213198  0.90659898 0.89238579 0.90761421] |
|                         |                                                          |
| Average Precision Score |                    0.9061012601503527                    |
|                         |                                                          |
|       Recall Score      | [0.90258752 0.9213198  0.90659898 0.89238579 0.90761421] |
|                         |                                                          |
|   Average Recall Score  |                    0.9061012601503527                    |
|                         |                                                          |
|         F1 Score        | [0.90258752 0.9213198  0.90659898 0.89238579 0.90761421] |
|                         |                                                          |
|     Average F1 Score    |                    0.9061012601503527                    |
+-------------------------+----------------------------------------------------------+

In [251]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [252]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.961023,0.961023,0.961023,0.961023,0.961066,0.922053,0.020669
1,K-Nearest Neighbours,0.957369,0.957369,0.957369,0.957369,0.957472,0.914821,0.124753
2,Support Vector Machine,0.954933,0.954933,0.954933,0.954933,0.955117,0.910129,3.358393
3,Naive Bayes Classifier,0.925700,0.925700,0.925700,0.925700,0.926038,0.852255,0.015903
4,Logistic Regression,0.926106,0.926106,0.926106,0.926106,0.926383,0.852804,0.067204
5,Multi Layer Perceptron,0.967113,0.967113,0.967113,0.967113,0.967273,0.934423,14.866977
6,AdaBoost Classifier,0.935039,0.935039,0.935039,0.935039,0.935277,0.870522,0.367308
7,Random Forest,0.968737,0.968737,0.968737,0.968737,0.968857,0.937585,0.382865
8,Gradient Boosting,0.945189,0.945189,0.945189,0.945189,0.945343,0.890568,0.571598
9,Extra Trees,0.972391,0.972391,0.972391,0.972391,0.972451,0.944806,0.436831
10,Custom Naive Bayes Classifier,0.925700,0.925700,0.925700,0.925700,0.926038,0.852255,2.198473
11,Count-Based Classifier,0.905400,0.905400,0.905400,0.905400,0.906327,0.816459,1.188854

# 20. Monkey-Pox Patients Dataset

In [253]:
# Loading the dataset
df = pd.read_csv("datasets/monkey-pox.csv")

In [254]:
# Displaying the first five records of the dataset
df.head()

,Patient_ID,Systemic Illness,Rectal Pain,Sore Throat,Penile Oedema,Oral Lesions,Solitary Lesion,Swollen Tonsils,HIV Infection,Sexually Transmitted Infection,MonkeyPox
0,P0,None,False,True,True,True,False,True,False,False,Negative
1,P1,Fever,True,False,True,True,False,False,True,False,Positive
2,P2,Fever,False,True,True,False,False,False,True,False,Positive
3,P3,None,True,False,False,False,True,True,True,False,Positive
4,P4,Swollen Lymph Nodes,True,True,True,False,False,True,True,False,Positive

In [255]:
# Dropping unwanted columns
df.drop(['Patient_ID'], axis=1, inplace=True)

In [256]:
# Displaying the first five records of the dataset
df.head()

,Systemic Illness,Rectal Pain,Sore Throat,Penile Oedema,Oral Lesions,Solitary Lesion,Swollen Tonsils,HIV Infection,Sexually Transmitted Infection,MonkeyPox
0,None,False,True,True,True,False,True,False,False,Negative
1,Fever,True,False,True,True,False,False,True,False,Positive
2,Fever,False,True,True,False,False,False,True,False,Positive
3,None,True,False,False,False,True,True,True,False,Positive
4,Swollen Lymph Nodes,True,True,True,False,False,True,True,False,Positive

In [257]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(25000, 10)

In [258]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [259]:
# Checking the instance counts of the target attribute
df['MonkeyPox'].value_counts()

Positive    15909
Negative     9091
Name: MonkeyPox, dtype: int64

In [260]:
# Encoding the attributes of the dataset
df = encoding(df)

In [261]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [262]:
# Separating dependent and independent variables
X, y = separating(df, 'MonkeyPox')

In [263]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [264]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [265]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.63739933 0.64113141 0.62973875 0.62168533 0.62848723] |
|                         |                                                          |
|  Average Accuracy Score |                    0.6316884104195586                    |
|                         |                                                          |
|     Precision Score     | [0.63739933 0.64113141 0.62973875 0.62168533 0.62848723] |
|                         |                                                          |
| Average Precision Score |                    0.6316884104195586                    |
|                         |                                                          |
|       Recall Score      | [0.63739933 0.64113141 0.62973875 0.62168533 0.62848723] |
|                         |                                                          |
|   Average Recall Score  |                    0.6316884104195586                    |
|                         |                                                          |
|         F1 Score        | [0.63739933 0.64113141 0.62973875 0.62168533 0.62848723] |
|                         |                                                          |
|     Average F1 Score    |                    0.6316884104195586                    |
+-------------------------+----------------------------------------------------------+

In [266]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [267]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.646292,0.646292,0.646292,0.646292,0.646312,0.292639,0.028737
1,K-Nearest Neighbours,0.613922,0.613922,0.613922,0.613922,0.613873,0.227841,0.377598
2,Support Vector Machine,0.642678,0.642678,0.642678,0.642678,0.642569,0.285718,81.335271
3,Naive Bayes Classifier,0.642835,0.642835,0.642835,0.642835,0.642818,0.285650,0.020251
4,Logistic Regression,0.611565,0.611565,0.611565,0.611565,0.611570,0.223140,0.035428
5,Multi Layer Perceptron,0.642049,0.642049,0.642049,0.642049,0.641801,0.286598,11.959559
6,AdaBoost Classifier,0.642363,0.642363,0.642363,0.642363,0.642385,0.284788,0.486277
7,Random Forest,0.643463,0.643463,0.643463,0.643463,0.643394,0.287027,0.792202
8,Gradient Boosting,0.645820,0.645820,0.645820,0.645820,0.645666,0.292523,0.897587
9,Extra Trees,0.646292,0.646292,0.646292,0.646292,0.646312,0.292639,0.963062
10,Custom Naive Bayes Classifier,0.642835,0.642835,0.642835,0.642835,0.642818,0.285650,1.686263
11,Count-Based Classifier,0.632307,0.632307,0.632307,0.632307,0.632462,0.265977,0.899229

# 21. Animal Condition Classification Dataset

In [268]:
# Loading the dataset
df = pd.read_csv("datasets/animal-condition.csv")

In [269]:
# Displaying the first five records of the dataset
df.head()

,AnimalName,symptoms1,symptoms2,symptoms3,symptoms4,symptoms5,Dangerous
0,Dog,Fever,Diarrhea,Vomiting,Weight loss,Dehydration,Yes
1,Dog,Fever,Diarrhea,Coughing,Tiredness,Pains,Yes
2,Dog,Fever,Diarrhea,Coughing,Vomiting,Anorexia,Yes
3,Dog,Fever,Difficulty breathing,Coughing,Lethargy,Sneezing,Yes
4,Dog,Fever,Diarrhea,Coughing,Lethargy,Blue Eye,Yes

In [270]:
# Checking the unique values present in the dataset for the attribute 'AnimalName'
df['AnimalName'].value_counts()

Buffaloes            129
Sheep                110
Pig                   63
Fowl                  62
Elephant              59
Duck                  56
Deer                  38
Donkey                38
Birds                 37
cat                   36
Dog                   34
Monkey                28
Goat                  26
Cattle                21
Hamster               18
Tiger                 17
Lion                  16
Rabbit                11
Horse                 10
Chicken                9
Fox                    7
Other Birds            6
horse                  5
chicken                4
Turtle                 4
Pigs                   3
cow                    3
donkey                 2
Goats                  2
White-tailed deer      1
Hyaenas                1
Wolves                 1
Dogs                   1
Fox                    1
Moos                   1
Reindeer               1
mammal                 1
Sika deer              1
cattle                 1
Mule deer              1
Wapiti                 1
Elk                    1
mules                  1
duck                   1
snake                  1
Black-tailed deer      1
Name: AnimalName, dtype: int64

In [271]:
# Fixing the values of the attribute 'AnimalName'
df['AnimalName'] = [name.lower() for name in df['AnimalName']]
df['AnimalName'].replace({'black-tailed deer':'deer','white-tailed deer':'deer','mule deer':'deer','sika deer':'deer','reindeer':'deer','elk':'deer','wapiti':'deer','mules':'horse','other birds': 'birds','pigs':'pig', 'dogs': 'dog', 'goats': 'goat'}, inplace = True)

In [272]:
# Displaying the first five records of the dataset
df.head()

,AnimalName,symptoms1,symptoms2,symptoms3,symptoms4,symptoms5,Dangerous
0,dog,Fever,Diarrhea,Vomiting,Weight loss,Dehydration,Yes
1,dog,Fever,Diarrhea,Coughing,Tiredness,Pains,Yes
2,dog,Fever,Diarrhea,Coughing,Vomiting,Anorexia,Yes
3,dog,Fever,Difficulty breathing,Coughing,Lethargy,Sneezing,Yes
4,dog,Fever,Diarrhea,Coughing,Lethargy,Blue Eye,Yes

In [273]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(871, 7)

In [274]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [275]:
# Checking the instance counts of the target attribute
df['Dangerous'].value_counts()

Yes    849
No      20
Name: Dangerous, dtype: int64

In [276]:
# Encoding the attributes of the dataset
df = encoding(df)

In [277]:
# Imputing the missing values if any by replacing it with the mode
df = imputation(df)

In [278]:
# Separating dependent and independent variables
X, y = separating(df, 'Dangerous')

In [279]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [280]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.97142857 0.98561151 0.97841727 0.97122302 0.97122302] |
|                         |                                                          |
|  Average Accuracy Score |                    0.9755806783144912                    |
|                         |                                                          |
|     Precision Score     | [0.97142857 0.98561151 0.97841727 0.97122302 0.97122302] |
|                         |                                                          |
| Average Precision Score |                    0.9755806783144912                    |
|                         |                                                          |
|       Recall Score      | [0.97142857 0.98561151 0.97841727 0.97122302 0.97122302] |
|                         |                                                          |
|   Average Recall Score  |                    0.9755806783144912                    |
|                         |                                                          |
|         F1 Score        | [0.97142857 0.98561151 0.97841727 0.97122302 0.97122302] |
|                         |                                                          |
|     Average F1 Score    |                    0.9755806783144912                    |
+-------------------------+----------------------------------------------------------+

In [281]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [282]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.977143,0.977143,0.977143,0.977143,0.741329,0.343281,0.006908
1,K-Nearest Neighbours,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.007675
2,Support Vector Machine,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.011817
3,Naive Bayes Classifier,0.971429,0.971429,0.971429,0.971429,0.738439,0.304254,0.003849
4,Logistic Regression,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.005700
5,Multi Layer Perceptron,0.994286,0.994286,0.994286,0.994286,0.750000,0.705072,0.449056
6,AdaBoost Classifier,0.994286,0.994286,0.994286,0.994286,0.750000,0.705072,0.088278
7,Random Forest,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.135995
8,Gradient Boosting,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.104753
9,Extra Trees,0.994286,0.994286,0.994286,0.994286,0.750000,0.705072,0.064246
10,Custom Naive Bayes Classifier,0.068571,0.068571,0.068571,0.068571,0.528902,0.026470,0.034218
11,Count-Based Classifier,0.988571,0.988571,0.988571,0.988571,0.500000,0.000000,0.026564

# 22. Android Malware Detection

In [283]:
# Loading the dataset
df = pd.read_csv("datasets/TUANDROMD.csv")

In [284]:
# Displaying the first five records of the dataset
df.head()

,ACCESS_ALL_DOWNLOADS,ACCESS_CACHE_FILESYSTEM,ACCESS_CHECKIN_PROPERTIES,ACCESS_COARSE_LOCATION,ACCESS_COARSE_UPDATES,ACCESS_FINE_LOCATION,ACCESS_LOCATION_EXTRA_COMMANDS,ACCESS_MOCK_LOCATION,ACCESS_MTK_MMHW,ACCESS_NETWORK_STATE,...,Landroid/telephony/TelephonyManager;->getLine1Number,Landroid/telephony/TelephonyManager;->getNetworkOperator,Landroid/telephony/TelephonyManager;->getNetworkOperatorName,Landroid/telephony/TelephonyManager;->getNetworkCountryIso,Landroid/telephony/TelephonyManager;->getSimOperator,Landroid/telephony/TelephonyManager;->getSimOperatorName,Landroid/telephony/TelephonyManager;->getSimCountryIso,Landroid/telephony/TelephonyManager;->getSimSerialNumber,Lorg/apache/http/impl/client/DefaultHttpClient;->execute,Label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,malware
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,malware
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,malware
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,malware
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,malware

In [285]:
# Displaying the shape of the dataset i.e. (no. of records, no. of attributes)
df.shape

(4465, 242)

In [286]:
# Converting '?' to NaN incase it is present in the dataset
df.replace('?', np.nan, inplace=True)

In [287]:
# Checking the instance counts of the target attribute
df['Label'].value_counts()

malware     3565
goodware     899
Name: Label, dtype: int64

In [288]:
# Encoding the attributes of the dataset
df = encoding(df)

In [289]:
# Imputing the missing values if any by using KNN Imputer
df = imputation(df)

In [290]:
# Separating dependent and independent variables
X, y = separating(df, 'Label')

In [291]:
# Handing class imbalance problem using SMOTEN
X, y = oversampling(X,y)

In [292]:
# Splitting the dataset in a 80:20 train-test split ratio
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [293]:
kfold_cross_validation(X_train, y_train)

*** Optimized Count-Based Classifier ***
+-------------------------+----------------------------------------------------------+
|    Evaluation Metric    |                          Value                           |
+-------------------------+----------------------------------------------------------+
|      Accuracy Score     | [0.76950044 0.79228747 0.80280456 0.85188431 0.76687117] |
|                         |                                                          |
|  Average Accuracy Score |                    0.796669588080631                     |
|                         |                                                          |
|     Precision Score     | [0.76950044 0.79228747 0.80280456 0.85188431 0.76687117] |
|                         |                                                          |
| Average Precision Score |                    0.796669588080631                     |
|                         |                                                          |
|       Recall Score      | [0.76950044 0.79228747 0.80280456 0.85188431 0.76687117] |
|                         |                                                          |
|   Average Recall Score  |                    0.796669588080631                     |
|                         |                                                          |
|         F1 Score        | [0.76950044 0.79228747 0.80280456 0.85188431 0.76687117] |
|                         |                                                          |
|     Average F1 Score    |                    0.796669588080631                     |
+-------------------------+----------------------------------------------------------+

In [294]:
# Classification and model evaluation
res = classification_evaluation(X_train, X_test, y_train, y_test)

XGBoost : value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

In [295]:
res[0]

,Model,Accu,Reca,Prec,F1,AUC,MCC,TT
0,Decision Tree,0.990189,0.990189,0.990189,0.990189,0.990053,0.980390,0.026679
1,K-Nearest Neighbours,0.990890,0.990890,0.990890,0.990890,0.991030,0.981816,0.110640
2,Support Vector Machine,0.992292,0.992292,0.992292,0.992292,0.992390,0.984597,1.553025
3,Naive Bayes Classifier,0.975473,0.975473,0.975473,0.975473,0.975810,0.951207,0.034382
4,Logistic Regression,0.989488,0.989488,0.989488,0.989488,0.989500,0.978960,0.061037
5,Multi Layer Perceptron,0.989488,0.989488,0.989488,0.989488,0.989331,0.978999,4.548448
6,AdaBoost Classifier,0.988788,0.988788,0.988788,0.988788,0.988862,0.977574,0.498974
7,Random Forest,0.990890,0.990890,0.990890,0.990890,0.990776,0.981784,0.218084
8,Gradient Boosting,0.990189,0.990189,0.990189,0.990189,0.990265,0.980379,0.812068
9,Extra Trees,0.991591,0.991591,0.991591,0.991591,0.991499,0.983179,0.279021
10,Custom Naive Bayes Classifier,0.975473,0.975473,0.975473,0.975473,0.975810,0.951207,9.446320
11,Count-Based Classifier,0.783462,0.783462,0.783462,0.783462,0.789796,0.632990,5.807505